### ISSUE TITLE
Attempting to run any spec runs `bundle exec rspec --color spec/b_spec.rb`

### ISSUE THREAD

**Issue by michaelwebb76** [thadeu/vscode-run-rspec-file#1]
I hope it's just me doing something dumb, but in case it's not?

(Any help to debug this would be greatly appreciated)

**Comment by michaelwebb76** [comment]
OK I'm pretty sure 8ba5fb28d8ac4acb8bfa8934028ab916e16e5459 broke things really badly.

Attempting to run a corresponding spec in your `app/models` folder works.
Attempting to run the same spec from **within the spec file** runs`spec/b_spec.rb`
Attempting to run a corresponding spec from any ruby file in the `lib` folder runs`spec/b_spec.rb`
Attempting to run any spec in the `spec/lib` folder runs`spec/b_spec.rb`

**Comment by michaelwebb76** [comment]
Have confirmed that going back to 0.4.0 has none of these problems

**Comment by alxckn** [comment]
Got the same issue, downgrading to 0.4.0 did the trick also.
For those who don't know (like me 5 minutes ago), it's possible to manage extensions' versions by right clicking on the extension and selecting `Install Another Version...` within vscode

**Comment by cmer** [comment]
Same problem here. Thanks for the workaround.

**Comment by thadeu** [comment]
@michaelwebb76 @alxckn @cmer I solved problem within version v0.5.3

**Comment by thadeu** [comment]
please, you feel free to re-open should it happen again!

**Comment by cmer** [comment]
It's working now. Thanks!

**Comment by thadeu** [comment]
@cmer :)
