### ISSUE TITLE
Can not run specs with "*rb" in the name  

### ISSUE THREAD

**Issue by tiagobabo** [thadeu/vscode-run-rspec-file#11]
I think you need to escape the `.` in the following regex:
https://github.com/thadeu/vscode-run-rspec-file/blob/063f608c79958af935c69c37b01f3032641d19f0/src/extension.ts#L33

Otherwise if you try to run a spec called `leaderboard_spec.rb` it will fail because it will remove the `erb` substring and try to run `leadoard_spec.rb`

**Comment by thadeu** [comment]
@tiagobabo I'll be happy if you open pull request for this :)
