### ISSUE TITLE
Return to calling window after shortcut keypress

### ISSUE THREAD

**Issue by jayshepherd** [thadeu/vscode-run-rspec-file#12]
When using a shortcut to fire off a test in the terminal, it would be nice to come back to where you were.

I use vim keybindings, so I'm heavy on the keyboard for navigation, but typing right after the shortcut to run the rspec test I find myself typing in the terminal.

If I don't delete what I've typed, a subsequent shortcut to run the commands will include those characters.

**Comment by thadeu** [comment]
@jayshepherd for being a specific case to use in VIM, could you give an idea of what the problem might be?

**Comment by thadeu** [comment]
@jayshepherd this new version has support for toggle file https://marketplace.visualstudio.com/items?itemName=Thadeu.vscode-run-rspec-file

thanks for open issue
