### ISSUE TITLE
Add toggle file option

### ISSUE THREAD

**Issue by kulas115** [thadeu/vscode-run-rspec-file#13]
Hi 👋🏼 I really enjoy using this extension so thanks for all the hard work. After months of usage, I feel like there is one important use case missing. While you can `Search and Run Spec based current file` you cannot go back to this file using a shortcut. In big projects, it causes friction when you want to quickly see the file you are actually testing.

Is this something that could be easily added? I've found [another extension](https://github.com/malt03/rails-rspec-file-toggle) that does that but adding it just for the sake of `toggle` functionality does not make much sense and it would be rad to have it here.

Thanks!

**Comment by thadeu** [comment]
Hi @kulas115 First, thanks for open the issue!

So,  It's a great idea, and something relatively easy to do. I will put it in the backlog and do it as soon as possible. The issue will remain open until I have done it.

**Comment by thadeu** [comment]
@kulas115 Which shortcut do you feel most comfortable using in this scenario?

**Comment by thadeu** [comment]
@kulas115 this new version v0.5.9 has support for file toggle. https://marketplace.visualstudio.com/items?itemName=Thadeu.vscode-run-rspec-file

Thanks for all.

**Comment by kulas115** [comment]
@thadeu you are a ⭐ Thank you for adding that feature so quickly!
