### ISSUE TITLE
When 'spec' is in the rspec file's path (folder), it gets stripped out in the rspec command

### ISSUE THREAD

**Issue by andy-peavy-wowza** [thadeu/vscode-run-rspec-file#14]
One test repo we have has a folder named `bat_spec`.  
Folder structure:
- lib
- spec
  - bat_spec
    - header
    - footer
    - ...(etc)

So when running an rspec file from that folder, the command line ends up being: 
`bundle exec rspec --color spec/bat_header/header_spec.rb`
But should be:
`bundle exec rspec --color spec/bat_spec/header/header_spec.rb`

**Comment by thadeu** [comment]
the word "spec" is a reserved word and therefore should not be in the name of folders.
try switching "specs" or "test" and see the result

**Comment by thadeu** [comment]
another point, vscode can create create spec file based on the original file, so you avoid creating non-relative nests

**Comment by thadeu** [comment]
Closing issue for inactive time
