### ISSUE TITLE
Feature Request: run spec for all open spec files

### ISSUE THREAD

**Issue by Osseta** [thadeu/vscode-run-rspec-file#20]
When I working I will open on the editor all the relevant spec files to the task at hand. Would be good to run a command that runs all the spec files currently open in the editor rather than running each one by one.

if I have the following files open in vscode:
* app/models/widget.rb
* spec/models/widget_spec.rb
* spec/controllers/widget_controller_spec.rb

Running the command would execute:

bundle exec rspec --color spec/models/widget_spec.rb spec/controllers/widget_controller_spec.rb

**Comment by thadeu** [comment]
Interesting... do you need this yet?

**Comment by Osseta** [comment]
I would love this feature. Was lamenting the lack only last week when refactoring some spec helpers and having to run affected files individually. We have a very large monolith and running all specs takes over an hour locally. (We run massively parallel in CI)

**Comment by thadeu** [comment]
@Osseta Cool! I'll work today in this feature. I hope release coming soon.

The ideia will be: All open files with `_spec.rb` must be execute, right?

**Comment by thadeu** [comment]
This feature will be included in this PR https://github.com/thadeu/vscode-run-rspec-file/pull/25

Thanks @Osseta for your request!

**Comment by thadeu** [comment]
@Osseta v0.5.27 Contains this features, use `cmd+option+j` to scan opened files and run rspec command

**Comment by Osseta** [comment]
This is working perfectly 💯 . Thank you so much.
