### ISSUE TITLE
Question / Feature request: Using existing terminal

### ISSUE THREAD

**Issue by danielolivaresd** [thadeu/vscode-run-rspec-file#21]
Note: I'm not sure if this is possible, as I'm quite new to VS Code.

Is there a way that the rspec command runs on an existing (open) terminal? Maybe it would be a useful setting to avoid opening a new one and having to deal with it.

**Comment by thadeu** [comment]
Hey @danielolivaresd thanks for open this issue.
So, I'm not sure as well. But I will search about this and talk about more. Ok?

We going to talk more

**Comment by zarembas** [comment]
@thadeu Have you had the chance to look into this? I'm trying to avoid this issue: 
<img width="180" alt="Screenshot 2023-08-16 at 11 53 35" src="https://github.com/thadeu/vscode-run-rspec-file/assets/1636476/d888c66d-c4b3-4601-844e-c6ca2e467713">

**Comment by thadeu** [comment]
@vassyz In Theory we use one terminal, because we make replace in the current terminal with the same name.

I'll investigate this issue and create a new version if necessary.

**Comment by thadeu** [comment]
@vassyz Can you could update extension and test again?

**Comment by zarembas** [comment]
@thadeu tested with the latest version and can confirm that the specs run in the same tab. Thank you! 🙇
