### ISSUE TITLE
Auto-create file for controllers should create a request spec (or be configurable)

### ISSUE THREAD

**Issue by davidalejandroaguilar** [thadeu/vscode-run-rspec-file#23]
Hi,

As you may already know, controller specs are deprecated, from the [release notes](http://rspec.info/blog/2016/07/rspec-3-5-has-been-released/):

>For new Rails apps: we don't recommend adding the rails-controller-testing gem to your application. The official recommendation of the Rails team and the RSpec core team is to write request specs instead. Request specs allow you to focus on a single controller action, but unlike controller tests involve the router, the middleware stack, and both rack requests and responses. This adds realism to the test that you are writing, and helps avoid many of the issues that are common in controller specs. In Rails 5, request specs are significantly faster than either request or controller specs were in rails 4, thanks to the work by Eileen Uchitelle1 of the Rails Committer Team.

Thus, whenever we auto-create a controller spec via the extension's "create file" feature, instead of creating the file in `spec/controllers`, it should create it in `spec/requests`. Or at least, this should be configurable.

---

I'm not familiar with the codebase but let me know how I can help.

**Comment by davidalejandroaguilar** [comment]
Added a PR 😃

**Comment by thadeu** [comment]
@davidalejandroaguilar Can you check your PR?
