### ISSUE TITLE
Toggling from test to file with suffix and folder used for minitest does not work 

### ISSUE THREAD

**Issue by lioneldebauge** [thadeu/vscode-run-rspec-file#26]
### Expected behavior

Using this settings
```
{
  "vscode-run-rspec-file.folder": "test",
  "vscode-run-rspec-file.suffix": "test",
}
```

I should be able to toggle back and forth from a classic minitest file tree structure. 

### Current behavior

Given my project tree structure

```
app/models/some_file.rb
test/models/some_file_test.rb
```

I cannot toggle from a test file back to the original file. I get redirected to a file that does not exist named `test/_test.rb`

### Investigation

After looking at the source code I believe this is due to the following function

```ts
function getAsRelativePath(): string {
  const workspaceProjectPath: string = getWorkspacePath()
  const rootFile: string = getFilename().replace(workspaceProjectPath, '')
  const isApp: boolean = /^\/app\//.test(rootFile)
  const isSpec: boolean = /^\/spec\//.test(rootFile)
  const isLib: boolean = /^\/lib\//.test(rootFile)

  if (isApp) {
    const indexOfAppFolder: number = rootFile.indexOf('/app/')
    return rootFile.substr(indexOfAppFolder + 1)
  } else if (isSpec) {
    const indexOfSpecFolder: number = rootFile.indexOf('/spec/')
    return rootFile.substr(indexOfSpecFolder + 1)
  } else if (isLib) {
    const indexOfLibFolder: number = rootFile.indexOf('/lib/')
    return rootFile.substr(indexOfLibFolder + 1)
  }

  return ''
}
```

It seems that this function will always return an empty string given that it does not check for a custom spec folder given in the settings. What do you think ? My TS coding skills are close to 0 but I can try to open a PR

PS: thanks for this awesome VS Code extension, I use it nearly every day 👍

**Comment by thadeu** [comment]
@lioneldebauge Great. Thanks for first investigation. I'll investigate and fix this.

**Comment by lioneldebauge** [comment]
Great, let me know if I can help you  !

**Comment by thadeu** [comment]
@lioneldebauge Can you could update extension and test again?

**Comment by lioneldebauge** [comment]
@thadeu I can now toggle from a test file back to the original file. However I cannot do the opposite: toggle from the original file to a test file. I get redirected to a file with a "spec" suffix. 

Example
```
user.rb  -> user_spec.rb
# should be user_test.rb
```

Same settings as previously

```ruby
{
  "vscode-run-rspec-file.folder": "test",
  "vscode-run-rspec-file.suffix": "test",
}
```

**Comment by thadeu** [comment]
@lioneldebauge Are you using Rails application or another app?

**Comment by thadeu** [comment]
@lioneldebauge Do you send me which version is installed for you?

You can get it here.

<img width="564" alt="image" src="https://github.com/thadeu/vscode-run-rspec-file/assets/77889/6f3e1482-9b0b-4aa1-87f7-1ff540f6e72d">

**Comment by lioneldebauge** [comment]
v0.6.1 installed and I'm indeed using a Rails application

**Comment by thadeu** [comment]
@lioneldebauge I believe this issue related with #27, so can you update your extension to 0.6.2 and test again?

It's necessarily Reload Window on VSCode

**Comment by lioneldebauge** [comment]
@thadeu it works with the new version ! Many thanks :)
