### ISSUE TITLE
The "Custom Command" option does not work after updating to v0.5.29.

### ISSUE THREAD

**Issue by jsice** [thadeu/vscode-run-rspec-file#27]
## Expected behavior
When using these settings:
```
{
    "vscode-run-rspec-file.custom-command": "test"
}
```
It should run the command "test path/to/file_spec.rb".

## Current behavior
Instead, it runs the command "bundle exec rspec --color path/to/file_spec.rb".

Am I missing something?

**Comment by thadeu** [comment]
@jsice Can you could update extension and test again?

**Comment by zarembas** [comment]
@thadeu  I'm on version `v0.6.1` and `"vscode-run-rspec-file.custom-command": "bin/rspec",` is not working for me. Instead I'm still getting the default `bundle exec rspec --color`

**Comment by thadeu** [comment]
#29 This PR will be solve this

**Comment by zarembas** [comment]
@thadeu Thanks! Sorry, checked existing issues but didn't look at the opened PRs.

**Comment by thadeu** [comment]
@vassyz @jsice I release a new version v0.6.2 to fix this issue. 

Can you update extension and test again?

**Comment by zarembas** [comment]
Tested and it works. Thank you! 🙇

**Comment by thadeu** [comment]
@vassyz Great, thanks for your patience. Enjoy
