### ISSUE TITLE
RSpec Extension: parse settings.json failed - v0.6.2

### ISSUE THREAD

**Issue by davidalejandroaguilar** [thadeu/vscode-run-rspec-file#30]
I'm getting this error on 0.6.2:

```
RSpec Extension: parse settings.json failed
```

I didn't change any settings and I even tried with an empty settings.json file:

```json
{}
```

Think something was broken by accident?

The extension still works as expected, except that the new setting for controller specs is not respected https://github.com/thadeu/vscode-run-rspec-file/pull/24 with these settings:

```json
{
  "vscode-run-rspec-file.controller-spec-directory": "requests"
}
```

**Comment by nvanoorschot** [comment]
I run into the same exception since the 0.6.2 update, but cannot get the extension to work at all. Even when removing all custom settings it still fails.

VScode also reports another exception about not being able to launch the terminal process. What I notice about that message is that it mentions the full path to my project folder without the leading forward slash, making it a relative path.

```
The terminal process failed to launch: Starting directory (cwd) "home/me/projects/project" does not exist.
```

**Comment by nvanoorschot** [comment]
The issue I run into also manifests in version 0.6.1. Downgrading the extension to 0.5.x fixes it for me for now.

**Comment by thadeu** [comment]
Interesting, I'll create this scenario and then fixed them.

**Comment by thadeu** [comment]
I release a new version (v0.6.3) on the Marketplace.

@nvanoorschot @davidalejandroaguilar Can you update your extension and test again?

After update, it's necessary Reload Window on VSCode

**Comment by davidalejandroaguilar** [comment]
@thadeu That fixed it, thank you!

I'm going to mark it as closed, but everyone else, feel free to re-open if that's not the case for you.

**Comment by Paul-Bob** [comment]
> I run into the same exception since the 0.6.2 update, but cannot get the extension to work at all. Even when removing all custom settings it still fails.
> 
> VScode also reports another exception about not being able to launch the terminal process. What I notice about that message is that it mentions the full path to my project folder without the leading forward slash, making it a relative path.
> 
> ```
> The terminal process failed to launch: Starting directory (cwd) "home/me/projects/project" does not exist.
> ```

Same here, none version bigger than `v0.5.29` works for me.

Error: `The terminal process failed to launch: Starting directory (cwd) "home/bob/Projects/gems/avo" does not exist.`

**Comment by thadeu** [comment]
@Paul-Bob Can you send me tree view for your vscode?

**Comment by Paul-Bob** [comment]
@thadeu this helps? Not sure what do you mean by "tree view"

![image](https://github.com/thadeu/vscode-run-rspec-file/assets/69730720/99d299b4-b7b9-4134-9a1a-34896a627dbe)

**Comment by zarembas** [comment]
I'm still getting this error: `RSpec Extension: parse settings.json failed` every time I run a spec for the first time.

**Comment by zarembas** [comment]
If anyone encounters the error mentioned above, in my case, it was caused by a trailing comma on the last line of the project’s `.vscode/settings.json` file.
