### ISSUE TITLE
"Run File|Line on Rspec" is now prefixing app/ in the path causing "cannot load such file" error

### ISSUE THREAD

**Issue by zmoazeni** [thadeu/vscode-run-rspec-file#31]
Hello there!

I've been using your extension for a while. Thank you for it! It's so simple and useful.

The recent updates however have broken my environment. When I use the `Run File on Rspec` or `Run Line on Rspec` commands they are now prefixing `app/` to the path of the rspec file causing rspec to fail by not finding the file.

```
# before
bundle exec rspec --color spec/path/to/spec.rb

# recent changes
bundle exec rspec --color app/spec/path/to/spec.rb 
```

_Note, I have custom-command set to `bundle exec rspec --color`_

**Comment by kuboon** [comment]
I think this change is the problem.

https://github.com/thadeu/vscode-run-rspec-file/commit/3907cec46e3a7784f49055ec230a3511b5cb35ff#diff-7228073578feb141b2f4b232852373fe22f621ff167ef4642f1e5135cbb33f18

**Comment by thadeu** [comment]
That's so confuse, because no anyone receive error, only you.

I some questions for you.

What S.O do you use? (Win, Linux or Mac)

Do you use many folders in the workspace OR just one folder/project?

When you use reverse command it's happen too? For example, you have spec/path/to/spec.rb and run command line (cmd+l) it's works?

**Comment by zmoazeni** [comment]
@thadeu 

> What S.O do you use? (Win, Linux or Mac)

I'm on Mac M1

> Do you use many folders in the workspace OR just one folder/project?

Just one folder. I'm opening up a directory from the CLI: `code path/to/rails/app`

> When you use reverse command it's happen too? For example, you have spec/path/to/spec.rb and run command line (cmd+l) it's works?

Yep, works grand as long as I snip the added `app` prefix. I have also noticed that it seems that I sometimes the extension starts the terminal current working directory to the parent directory too. I wonder if that's part of the problem.

**Comment by sasharevzin** [comment]
Same for me, in my case I'm using .devcontainer that has `/app` for app

**Comment by thadeu** [comment]
I dont know .devcontainer @sasharevzin it's a docker?

Wow, we have many kinds to run our tests. So, I will happy if someone create a PR to fix this.

**Comment by sasharevzin** [comment]
yah, it's like running vscode inside of a container https://code.visualstudio.com/docs/devcontainers/containers

**Comment by astanimirov** [comment]
I am having the same issue since my VSCode got updated. I cannot use this extension because of the `app` issue. Do you know if someone is working on a fix?

**Comment by thadeu** [comment]
@astanimirov I'm fixing this error coming soon.

**Comment by thadeu** [comment]
I was launched a new relase 0.6.10, in order to fix that. If you use devcontainer, probably will not have problems more.

You can feel free to reopen issue if you have any problems. Thanks guys

**Comment by astanimirov** [comment]
@thadeu I confirm that it is fixed, thank you, it is much appreciated!

**Comment by thadeu** [comment]
@astanimirov 🎉
