### ISSUE TITLE
Support for Rails app with multiple engines

### ISSUE THREAD

**Issue by Andy9822** [thadeu/vscode-run-rspec-file#32]
Hey @thadeu, I just stumbled upon your super cool extension today and I really wanted to adopt it in my daily workflow.

I tried to configure it for my current company's Rails project but it seems it doesn't work so well with multi-engine apps 😢 
What I ended up having to do is set a custom `"vscode-run-rspec-file.custom-command": "script/vscode_rspec_runner.sh"` that points to a shell script in which all the magic tricks happen 🪄 

Do you have any intention of supporting multiple engines-based Rails apps? - I'd be willing to help you with that 

For the next weeks, I'll use the extension with this `custom-command` pointing to a shell script hack, although it's not ideal.
If it ends up proving to work just fine and the rest of the team enjoys it, I might consider even doing a whole fork to fully adapt it to our needs. However, ideally, I'd like to contribute to this extension since it seems pretty famous and other people could benefit from it too.

**Comment by thadeu** [comment]
Hey @Andy9822 Thanks for your issue.

I need to understand your workflow to adapt our extension. What do you say when say multi-engine? I meaning, do you have many rails app in the same folder, is it? I'm little confused about it.

**Comment by Andy9822** [comment]
Closing it since I managed to fully workaround it in my side.
Thanks for the super cool extension anyways!!
