### ISSUE TITLE
Extension fails with "The terminal process failed to launch" error

### ISSUE THREAD

**Issue by rafaeelaudibert** [thadeu/vscode-run-rspec-file#33]
I'm trying this extension now but I can't seem to make it work.

I'm running VSCode inside WSL2 (Ubuntu 22.04) and whenever I try running any of the actions (such as "RSpec > Run Line on RSpec") I get the following error:

![image](https://github.com/thadeu/vscode-run-rspec-file/assets/32079912/487d8443-9186-458e-a363-6399fd0e4a9c)

I believe the error is that `/` is not being appended at the beginning of the file path, such that it's looking for a relative folder instead of treating it as an absolute path. I tried checking how the extension does it, but the approach is reasonable here 

https://github.com/thadeu/vscode-run-rspec-file/blob/master/src/extension.ts#L11-L31

Do you have any ideas on what could be happening @thadeu?

**Comment by rafaeelaudibert** [comment]
This fixes the problem:

```diff
diff --git a/src/extension.ts b/src/extension.ts
index aa3e3b4..c749c18 100644
--- a/src/extension.ts
+++ b/src/extension.ts
@@ -19,14 +19,14 @@ function getTerminal(): vscode.Terminal {
       return opened
     }

-    return vscode.window.createTerminal({ name, cwd: workspace.path })
+    return vscode.window.createTerminal({ name, cwd: `/${workspace.path}` })
   }

   if (get(terminals, name)) {
     return get(terminals, name)
   }

-  terminals[name] = vscode.window.createTerminal({ name, cwd: workspace.path })
+  terminals[name] = vscode.window.createTerminal({ name, cwd: `/${workspace.path}` })
   return get(terminals, name)
 }
```

I'm fairly sure this isn't a comprehensible fix, though, because it'll break for everyone else that's working already. I think it might work if I try to detect if there's a leading slash or not. Wdyt @thadeu, would you be open to this PR?

You can test it on your local setup to see if it's working too

**Comment by rafaeelaudibert** [comment]
See #34

**Comment by olssonr** [comment]
I get the same error when running the extension in a devcontainer on a Debian image
