### ISSUE TITLE
Cursor compatibility

### ISSUE THREAD

**Issue by kaejul** [thadeu/vscode-run-rspec-file#39]
Has anyone been able to use this extension in Cursor?
The shortcuts cmd+alt+l and cmd+l are not working for me and i cant find the place to edit them.

Thank you for the awesome work

**Comment by thadeu** [comment]
Hey @garlou

You can create custom shortcuts if you dont want use the same keys that the Cursor.

But, I dont understand you, when you say: "i cant find the place to edit them".

You can modify shortcuts here.

<img width="640" alt="image" src="https://github.com/user-attachments/assets/e3585cd2-bdf3-4fca-a518-09d4a7221b3f">


>
> [!TIP]
> Also, the Cursos use prefix aichat to create shortcuts to himself, like this.
>

<img width="800" alt="image" src="https://github.com/user-attachments/assets/4d9c3fae-4f18-4fbc-b09d-9d19129015ad">

> [!NOTE]
> Let me know if you can modify your shortcuts, ok?

**Comment by thadeu** [comment]
I'll close this issue becuase I think that @garlou has already handled it.
